package zip.estrogen.mail.ui.theme

import androidx.compose.ui.graphics.Color

val RosePrimary = Color(0xFFBF3264)
val RoseOnPrimary = Color(0xFFFFFFFF)
val RoseContainerDark = Color(0xFF5A1730)
val RoseOnContainerDark = Color(0xFFFFD9E2)
val RoseContainerLight = Color(0xFFFFD9E2)
val RoseOnContainerLight = Color(0xFF3E0019)
val RoseLight = Color(0xFFE48AA9)

val PlumBackground = Color(0xFF1D171F)
val PlumSurface = Color(0xFF1D171F)
val PlumSurfaceDim = Color(0xFF171116)
val PlumSurfaceBright = Color(0xFF3F3640)
val PlumSurfaceContainerLowest = Color(0xFF120D14)
val PlumSurfaceContainerLow = Color(0xFF251E27)
val PlumSurfaceContainer = Color(0xFF29222B)
val PlumSurfaceContainerHigh = Color(0xFF342C36)
val PlumSurfaceContainerHighest = Color(0xFF3F3741)
val PlumSurfaceVariant = Color(0xFF4F424B)
val PlumOnSurfaceVariant = Color(0xFFD3C0CB)
val PlumOutline = Color(0xFF9C8B95)
val PlumOutlineVariant = Color(0xFF4F424B)

val WarmTextStrong = Color(0xFFFFFFFF)
val WarmTextDefault = Color(0xFFFAECF2)
val WarmTextSubtle = Color(0xFFD3C0CB)

val SecondaryDark = Color(0xFFE3BDC9)
val OnSecondaryDark = Color(0xFF422634)
val SecondaryContainerDark = Color(0xFF5A3C4A)
val OnSecondaryContainerDark = Color(0xFFFFD9E2)
val TertiaryDark = Color(0xFFEFBD94)
val OnTertiaryDark = Color(0xFF48280C)
val TertiaryContainerDark = Color(0xFF623F20)
val OnTertiaryContainerDark = Color(0xFFFFDCC2)

val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)

val LightBackground = Color(0xFFFFF8F8)
val LightSurface = Color(0xFFFFF8F8)
val LightSurfaceDim = Color(0xFFE7D6DC)
val LightSurfaceBright = Color(0xFFFFF8F8)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFFFF0F3)
val LightSurfaceContainer = Color(0xFFFCEAEF)
val LightSurfaceContainerHigh = Color(0xFFF6E4E9)
val LightSurfaceContainerHighest = Color(0xFFF0DEE4)
val LightSurfaceVariant = Color(0xFFF2DDE3)
val LightOnSurfaceVariant = Color(0xFF514347)
val LightOutline = Color(0xFF837377)
val LightOutlineVariant = Color(0xFFD5C2C8)
val LightTextDefault = Color(0xFF22191D)
val LightSecondary = Color(0xFF74565F)
val LightOnSecondaryContainer = Color(0xFF2B151D)
val LightTertiary = Color(0xFF7F5539)
val LightOnTertiaryContainer = Color(0xFF311300)
val LightError = Color(0xFFBA1A1A)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
